### ISSUE TITLE
Selected Date in Calender for Proposal is wrong

### ISSUE THREAD

**Issue by devnior69** [beefyfinance/beefy-vote#5]
If i select the 8 of Mai its getting selected in the Calender
![image](https://user-images.githubusercontent.com/83950980/119234732-aa4d9400-bb2f-11eb-8802-9d5607ab948b.png)

After confirmation it displays the 7 of Mai inside the form:
![image](https://user-images.githubusercontent.com/83950980/119234758-c0f3eb00-bb2f-11eb-8296-2144c72f4e15.png)

to correct the issue one solution inside Calender.vue is the following:

`
this.$emit('input', this.formatDate(year, month, day+1));
`

**Comment by ghost** [comment]
Dates are stored as unixtime, but displayed in local time.
Could this be related to an edge case in your timezone?

Can you share more information related to timezone, day and hour selected?
It works decently good for most users.
